#!/usr/bin/env zsh
setopt ERR_EXIT NULL_GLOB

system_locations=(system-root system-usr system-local system-opt)
user_locations=(user-local user-opt)
extra_locations=(test-install)

cd ${0:h}
if [[ ! -d test-dists ]] {
	mkdir test-dists
}
rm -rf test-dists/* test-dists/.*

function process {
	local location=$1
	local name=$2
	local display=$3
	local opts=${@[4,-1]}

	echo '======' Location: $display '======'
	outputdir=test-dists/uber@$name
	mkdir $outputdir $outputdir/build $outputdir/install
	./mk-dist \
		--uber-package \
		--location=$location \
		--build-dir=$outputdir/build \
		--output=$outputdir/dist.tgz \
		--install --install-dir $outputdir/install --install-mkdir \
		$opts
}
for location ($system_locations $user_locations $extra_locations) {
	process $location $location $location $@
}
for location ($user_locations) {
	process $location ${location}_$USER "$location (absolute home, for $USER)" --user-absolute-home=$HOME $@
}
process absolute@/absolute/path/ absolute "absolute@/absolute/path"
