#!/usr/bin/env zsh
setopt ERR_EXIT

cd ${0:h}
rm -rf test-install
mkdir test-install
mkdir test-install/bin test-install/libexec test-install/lib test-install/share
./mk-dist -v --location=test-install --install --uber-package
